### PR TITLE
Dot net core

### PR DESCRIPTION
**Pull request by MaitreDede**
Dotnet Core port of Jurassic

### CODE REVIEW

**Comment by paulbartrum** [comment]
Now that .NET core 2.0 has arrived, the port to .NET core is much simpler and with fewer compromises. I will close this PR.

**Comment by MaitreDede** [comment]
Ok. Do you mean `netstandard2.0` version of jurassic ?

**Comment by paulbartrum** [comment]
Yep.

**Comment by paulbartrum** [comment]
I've got all the projects moved to .NET core 2.0, except for the unit test projects. The only things that don't work are `DynamicILGenerator` (`ReflectionEmitILGenerator` can be used instead) and the ability to map source code to IL (for debugging support). Everything else seems to be working fine.

**Pull request closed without merging**
