### PR TITLE
Debug information added by external provider

### PR DESCRIPTION
**Pull request by thejonan**
Restored the debugging capabilities in a non-destructive way:
- A new interface takes the capabilities to provide different underlying emitters (`ISymbolHelper`) which is utilized in `MethodGenerator`.
- all `ENABLE_DEBUGGING` ifdefs are replaces with proper utilization of provided `SymbolHelper` in the ILGenerators as well.
- The Jurassic assembly is still .NET Standard compliant, but now the Engine is capable of receiving an external `SymbolHelperFactory`, which providers object compliant w/ `ISymbolHelper` which are plugged in the method generation process.
- There are two new projects in the solution - one is w/ the assembly (which is still .NET Framework 4.6.1 compatible), which only provides this debug aware symbol helper. The other project is a debug test bed.
- Few small cleanups and fixes are provided as well.

### CODE REVIEW

**Comment by paulbartrum** [comment]
I don't get it. Why do we need a factory provider model? Are you expecting there will be multiple ways to implement debug symbols?

**Comment by paulbartrum** [comment]
I've turned on ENABLE_DEBUGGING for .NET 4.5 builds of Jurassic and published a new NuGet package that contains the .NET 4.5 DLL. Does this meet your needs?

**Comment by thejonan** [comment]
The idea is to have .NET Core compatible assembly for running your JS code, because the final product can be deployed to any compatible platform. In the same time, during the debug sessions, one can _add_ one more assembly and get debugging enabled on his/her .NET Framework compatible development platform. And, yes, this potentially enables different ways of providing debugging symbols, without messing with the original running assembly.

Thanks, for bringing `ENABLE_DEBUGGING`  back. There were few other changes, which are making the debugging _much_ easier:
* Enabling the `SetLocalSymInfo()` - I've moved it from `public ReflectionEmitILLocalVariable(System.Reflection.Emit.LocalBuilder local, string name)` to `public override ILLocalVariable DeclareVariable(Type type, string name = null)`. This makes the local variables show up in the debugger.
* Adding virtual method `protected override string[] GetParameterNames()` so that `FunctionMethodGenerator` and `MethodGenerator` can provide different array of names - the (default) later case they are 3, but in functions calls - 5. The `GetParameterTypes()` is overridden and changed too.

**Comment by paulbartrum** [comment]
Thank you, I've made those changes in commit ae2d181dabfaa787c1c262c4058564ba980e3b0f.

**Pull request closed without merging**
